name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore src/YuriyGuts.RegexBuilder.sln
    
    - name: Build
      run: dotnet build src/YuriyGuts.RegexBuilder.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test src/YuriyGuts.RegexBuilder.sln --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: '**/test-results.trx'
